spring:
  profiles:
    active:
      - dev
---
spring:
  profiles: dev #开发环境
  application:
    name: sc-f-config-yangyi-dev

---
spring:
  profiles: test #测试环境
  application:
    name: sc-f-config-yangyi-test

#必须保存为 UTF-8 格式