spring:
  profiles:
    active:
      - dev

---
server:
  port: 8201
spring:
  profiles: dev
  application:
    name: sc-f-config-client

eureka:
  # Eureka 实例信息
  instance:
    instance-id: service-consumer-feign   #自定义服务名称的相关信息
    prefer-ip-address: true   #访问路径可以显示 IP 地址

  # Eureka 客户端信息
  client:
    #register-with-eureka: false  #服务消费者，不再注册自己？
    service-url:
      # 指明要注册到哪个 Eureka 服务中心
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/

---

server:
  port: 8202
spring:
  profiles: test
  application:
    name: sc-f-config-client

eureka:
  # Eureka 实例信息
  instance:
    instance-id: service-consumer-feign   #自定义服务名称的相关信息
    prefer-ip-address: true   #访问路径可以显示 IP 地址

  # Eureka 客户端信息
  client:
    #register-with-eureka: false  #服务消费者，不再注册自己？
    service-url:
      # 指明要注册到哪个 Eureka 服务中心
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
